// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";

export interface IGalleryFields {
  /** title */
  title: string;

  /** description */
  description?: string | undefined;

  /** photos */
  photos?: Asset[] | undefined;

  /** coverVertical */
  coverVertical?: Asset | undefined;

  /** coverHorizontal */
  coverHorizontal?: Asset | undefined;
}

export interface IGallery extends Entry<IGalleryFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "gallery";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE = "gallery";

export type IEntry = IGallery;

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
